"""
Central catalogue of all Toffoli decompositions.
"""

from circuits import (
    d1_barenco,
    d2_maslov,
    d3_amy,
    d4_cruz_linear,
    d5_nielsen_chuang,
    d6_selinger,
    d7_vale,
    d8_jones,
    d9_zero_ancilla,
    d10_alt,
)

CATALOGUE = [
    {
        "name": "D1_Barenco",
        "builder": d1_barenco.build,
        "verify": "operator",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        # Metadata
        "paper": "Barenco et al.",
        "year": 1995,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D2_Maslov",
        "builder": d2_maslov.build,
        "verify": "measurement",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D3_Amy",
        "builder": d3_amy.build,
        "verify": "operator",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D4_Cruz_Linear",
        "builder": d4_cruz_linear.build,
        "verify": "operator",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "relative_phase": False,
        "ancillas": 0,
        # IMPORTANT: this is the logical ordering implemented
        "logical_ccx": (0, 2, 1),
    },
    {
        "name": "D5_Nielsen_Chuang",
        "builder": d5_nielsen_chuang.build,
        "verify": "operator",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D6_Selinger",
        "builder": d6_selinger.build,
        "verify": "basis_state",
        "num_qubits": 7,
        "layout_type": 7,
        "data_qubits": [0, 1, 2],
        "exact": True,
        "relative_phase": False,
        "ancillas": 4,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D7_Vale",
        "builder": d7_vale.build,
        "verify": "measurement",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D8_Jones",
        "builder": d8_jones.build,
        "verify": "skip",
        "num_qubits": 4,
        "layout_type": 4,
        "data_qubits": None,
        "exact": False,
        "relative_phase": True,
        "ancillas": 1,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D9_Zero_Ancilla",
        "builder": d9_zero_ancilla.build,
        "verify": "operator",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
    {
        "name": "D10_Alt",
        "builder": d10_alt.build,
        "verify": "operator",
        "num_qubits": 3,
        "layout_type": 3,
        "data_qubits": None,
        "exact": True,
        "relative_phase": False,
        "ancillas": 0,
        "logical_ccx": (0, 1, 2),
    },
]